name: API tests
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      #Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      #checkout the repository 
      - name: Checkout code
        uses: actions/checkout@v4
      #restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore
      #biild the project
      - name: Build
        run: dotnet build
      #run API tests
      - name: Run API tests
        run: dotnet test /Users/lucy/Documents/Liudmyla_Savinska_Lib/Library.Test.Api/Library.Test.Api.csproj --logger "trx;LogFileName=test_results.trx" --results-directory /Users/lucy/Documents/Liudmyla_Savinska_Lib/Library.Test.Api/bin/Debug/net8.0/test-results